apiVersion: v1
kind: Service
metadata:
  name: api_service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      Port: 8000
      targetPort: 8000
      Node port: 30080
  Type: NodePort




